# Generated by Django 5.0.2 on 2024-04-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
